language: c

jobs:
  include:
    - name: Ubuntu 20.04 (GCC)
      os: linux
      dist: focal
      compiler: gcc
    - name: Ubuntu 20.04 (Clang)
      os: linux
      dist: focal
      compiler: clang
    - name: macOS 10.15.7 (Catalina, Xcode 12.0.1)
      os: osx
      osx_image: xcode12
      compiler: clang
    - name: macOS 11.1 (Big Sur, Xcode 12.3)
      os: osx
      osx_image: xcode12.3
      compiler: clang

env:
  - OMP_NUM_THREADS=4

addons:
  apt:
    packages:
      - libomp-dev
      - libopenmpi-dev
      - openmpi-bin
      - libgmp-dev
      - uuid-dev
  homebrew:
    packages:
      - libomp
      - open-mpi
      - gmp
      - ossp-uuid
      - argp-standalone
    update: true

before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" && $CC == "clang" ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH; fi

script:
  - cmake --version
  - cmake ./CMakeLists.txt
  - cmake --build .
  - ./aes256_test
  - ./ecc256_test
  - ./rbc_validator --usage
  - ./rbc_validator_mpi --usage
  - ./rbc_validator --help
  - ./rbc_validator_mpi --help
  - ./rbc_validator --mode=aes -rv -m3
  - |
    mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
      ./rbc_validator_mpi --mode=aes -rv -m3
  - ./rbc_validator --mode=aes -bv -m3
  - |
    mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
      ./rbc_validator_mpi --mode=aes -bv -m3
  - |
    [[ $(./rbc_validator --mode=aes -v -m3 \
        ddca0139c56a104940ecb16c9a64c689d18fa36c7d6bab71563dd0e540bdd028 \
        73962ffac2a737632b4e3dc0ce424dac \
        78df66c7-4723-434f-b5b9-ae61e02cd97c) == \
      "ddca0139c56a104940ecb16c9a64c689d18fa36c7d63aa71543dd0e540bdd028" ]]

  - |
    [[ $(mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
      ./rbc_validator_mpi --mode=aes -v -m3 \
        ddca0139c56a104940ecb16c9a64c689d18fa36c7d6bab71563dd0e540bdd028 \
        73962ffac2a737632b4e3dc0ce424dac \
        78df66c7-4723-434f-b5b9-ae61e02cd97c) == \
      "ddca0139c56a104940ecb16c9a64c689d18fa36c7d63aa71543dd0e540bdd028" ]]
  - ./rbc_validator --mode=ecc -rv -m2
  - |
    mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
      ./rbc_validator_mpi --mode=ecc -rv -m2
  - ./rbc_validator --mode=ecc -bv -m2
  - |
    mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
      ./rbc_validator_mpi --mode=ecc -bv -m2
  - |
    [[ $(./rbc_validator --mode=ecc -v -m2 \
        000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f \
        d253229db92099808ace5668aa3c1b182a3857ebacbee5e67eeb0f5e422a1ce90f1f52b9ba6ea8242d469c6208f8ba304056181a85406542bf3a89b5badb1cee) == \
      "100102030405060718090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f" ]]
  - |
    [[ $(mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
     ./rbc_validator_mpi --mode=ecc -v -m2 \
        000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f \
        d253229db92099808ace5668aa3c1b182a3857ebacbee5e67eeb0f5e422a1ce90f1f52b9ba6ea8242d469c6208f8ba304056181a85406542bf3a89b5badb1cee) == \
       "100102030405060718090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f" ]]

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/29fd40f0cf4a1a47b339
    # options: [always|never|change] default: always
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never